ci: prevent stack overflow on Windows when compiling triton-vm
Error I got in CI was:
error: failed to run custom build command for `triton-vm v2.0.0`

Caused by:
  process didn't exit successfully: `D:\a\neptune-wallet-app\neptune-wallet-app\src-tauri\target\release\build\triton-vm-5cee2eb57514dd3d\build-script-build` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
  --- stdout
  cargo::rerun-if-changed=build.rs

  --- stderr

  thread 'main' (7888) has overflowed its stack
warning: build failed, waiting for other jobs to finish...
failed to build app: failed to build app
       Error failed to build app: failed to build app
error Command failed with exit code 1.

This change should fix that error.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn ["tauri","build"]" failed with exit code 1